# repo-gitlab-iot-http.yaml
apiVersion: v1
kind: Secret
metadata:
  name: repo-gitlab-iot-http
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/root/iot.git
  username: root     # or "root" (not ideal), or a Project Access Token user
  password: xXMcztZpQM0cQB4O0HlqQ6qsA5bP076VGlkukG9rjTP0dXAt0XlJGn14EqGGAdBV       # prefer a Deploy Token or Project Access Token with read_repository
  # no TLS here (http), so no extra keys needed

