# -*- mode: ruby -*-
# vi: set ft=ruby :

# Read configuration from environment variables
LOGIN = ENV['LOGIN']
BOX_IMAGE = ENV['BOX_IMAGE']
SERVER_IP = ENV['SERVER_IP'] || '192.168.56.110'
VM_MEMORY = ENV['VM_MEMORY'] || '1024'
VM_CPUS = ENV['VM_CPUS'] || '1'

Vagrant.configure("2") do |config|
  # Common configuration
  config.vm.box = BOX_IMAGE

    server.vm.provider "virtualbox" do |vb|
        vb.memory = VM_MEMORY
        vb.cpus = VM_CPUS
    end

    config.vm.provider "parallels" do |prl|
        prl.cpus   = VM_CPUS
        prl.memory = VM_MEMORY
    end

  # Server VM
  config.vm.define "#{LOGIN}S" do |server|
    server.vm.hostname = "#{LOGIN}S"
    server.vm.network "private_network", ip: SERVER_IP

    # Forwarded ports
    server.vm.network "forwarded_port", guest: 80, host: 8080

    # Provision K3s server and deploy applications
    server.vm.provision "shell" do |s|
      s.path = "scripts/setup.sh"
      s.env = {
        "SERVER_IP" => SERVER_IP
      }
    end
  end
end
